services:
  course-management-frontend:
    image: course-management-frontend
    container_name: course-management-frontend
    build: .
    ports:
      - "3001:3001"
    networks:
      - web
networks:
  web:
    name: web
    driver: bridge
    
